apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-cpd-ws-runtimes-operator-sa
  namespace: {{ .Values.global.operatorNS }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - persistentvolumeclaims
      - persistentvolumeclaims/status
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ws.cpd.ibm.com
    resources:
      - notebookruntimes
      - notebookruntimes/status
      - notebookruntimes/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - runtimes.ibm.com
    resources:
      - runtimeassemblies
    verbs:
      - delete
      - get
      - list
      - patch
      - watch
