apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: non-olm-cp4d
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/nickmerrett/cp4d-5.2-gitops.git
    targetRevision: main
    path: .
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true