apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpd-wml-cluster-gitops
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/nickmerrett/cp4d-5.2-gitops.git
    targetRevision: main
    path: repos/cpd-wml/cluster-scope
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
