apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-cpd-wml-operator
  namespace: {{ .Values.global.operatorNS }}
  labels:
    null
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-cpd-wml-operator
  strategy: {}
  template:
    metadata:
      annotations:
        cloudpakId: eb9998dcc5d24e3eb5b6fb488f750fe2
        cloudpakName: IBM Cloud Pak for Data
        productID: eb9998dcc5d24e3eb5b6fb488f750fe2
        productMetric: FREE
        productName: IBM Watson Machine Learning
        productVersion: 5.2.0
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ibm-wml-cpd
        app.kubernetes.io/managed-by: ansible
        app.kubernetes.io/name: ibm-wml-cpd
        control-plane: ibm-cpd-wml-operator
        icpdsupport/addOnId: wml
        icpdsupport/app: operator
        icpdsupport/module: ibm-cpd-wml-operator
        intent: projected
        name: ibm-cpd-wml-operator
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
              weight: 3
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - args:
            - --zap-log-level
            - info
            - --max-concurrent-reconciles
            - "1"
            - --reconcile-period
            - 0s
          env:
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: WATCH_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: namespaces
                  name: namespace-scope
                  optional: true
            - name: WML_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ANSIBLE_STDOUT_CALLBACK
              value: yaml
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: ibm-cpd-wml-operator
            - name: REGISTRY_SECRET
              value: ibm-entitlement-key
            - name: ENTITLED_REGISTRY_NAME
              value: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com
          image: icr.io/cpopen/ibm-cpd-wml-operator@sha256:cab28e4c0a4387e013e68ded35960495d2c03ea8f4e9d7af2374c3725206082c
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: ibm-cpd-wml-operator
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 6789
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 256Mi
              memory: 1Gi
            requests:
              cpu: 100m
              ephemeral-storage: 256Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
      serviceAccountName: ibm-cpd-wml-operator-serviceaccount
