apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openpagesservices.openpages.cpd.ibm.com
spec:
  group: openpages.cpd.ibm.com
  names:
    kind: OpenPagesService
    listKind: OpenPagesServiceList
    plural: openpagesservices
    singular: openpagesservice
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: OpenPagesService is the Schema for the openpagesservices API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of OpenPagesService
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                autoScaleConfig:
                  type: boolean
                  description: Enable or Disable Horizontal pod autoscaling for all the instances
                  default: false
                version:
                  type: string
                  description: Addon version
                  default: "9.5.0"
                license:
                  properties:
                    accept:
                      type: boolean
                      description: Accept license? https://ibm.biz/openpages-license
                      enum:
                        - true
                  required: ["accept"]
                  type: object
                shutdown:
                  type: string
                  description: Shutdown the service and all instances
                  enum: ["true", "false", "force"]
              required: ["version", "license"]
            status:
              description: Status defines the observed state of OpenPagesService
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
