apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-opensearch-operator-controller-manager
  namespace: {{ .Values.global.instanceNS }}  
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - pods
      - pods/finalizers
      - pods/log
      - secrets
      - serviceaccounts
      - serviceaccounts/finalizers
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get

  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - issuers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - cert-manager.io
    resources:
      - certificates/status
    verbs:
      - get

  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - create
      - get
      - list

  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - opensearch.cloudpackopen.ibm.com
    resources:
      - clusters
      - nodepools
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - opensearch.cloudpackopen.ibm.com
    resources:
      - clusters/finalizers
      - nodepools/finalizers
    verbs:
      - update

  - apiGroups:
      - opensearch.cloudpackopen.ibm.com
    resources:
      - clusters/status
      - nodepools/status
    verbs:
      - get
      - patch
      - update

  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
