---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  labels:
    app.kubernetes.io/instance: ibm-cpd-openpages-operator
    app.kubernetes.io/managed-by: ibm-cpd-openpages-operator
    app.kubernetes.io/name: ibm-cpd-openpages-operator
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
      - batch
      - extensions
      - apps
      - policy
      - rbac.authorization.k8s.io
      - autoscaling
      - route.openshift.io
      - authorization.openshift.io
      - networking.k8s.io
      - metrics.k8s.io
    resources:
      - configmaps
      - secrets
      - pods
      - pods/exec
      - pods/log
      - services
      - jobs
      - deployments
      - deployments/scale
      - statefulsets
      - statefulsets/scale
      - persistentvolumeclaims
      - rolebindings
      - roles
      - routes
      - networkpolicies
      - cronjobs
      - horizontalpodautoscalers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for openpages.cpd.ibm.com/v1, Kind: OpenPagesService
  ##
  - apiGroups:
      - openpages.cpd.ibm.com
    resources:
      - openpagesservices
      - openpagesservices/status
      - openpagesservices/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for openpages.cpd.ibm.com/v1, Kind: OpenPagesInstance
  ##
  - apiGroups:
      - openpages.cpd.ibm.com
    resources:
      - openpagesinstances
      - openpagesinstances/status
      - openpagesinstances/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - zen.cpd.ibm.com
    resources:
      - zenservices
    verbs:
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - zen.cpd.ibm.com
    resources:
      - zenextension
      - zenextensions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - zen.cpd.ibm.com
    resources:
      - zenextension/status
      - zenextensions/status
    verbs:
      - get

  - apiGroups:
      - databases.cpd.ibm.com
    resources:
      - db2aaserviceservices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - rabbitmq.opencontent.ibm.com
    resources:
      - rabbitmqclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - operator.ibm.com
    resources:
      - operandrequests
      - operandregistries
      - operandconfigs
      - operandbindinfos
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  ##
  ## Rules for cpd.ibm.com/v1, Kind: Ibmcpd
  ##
  - apiGroups:
      - cpd.ibm.com
    resources:
      - ibmcpds
    verbs:
      - get
      - list
      - watch
# +kubebuilder:scaffold:rules
