---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
  labels:
    app.kubernetes.io/instance: ibm-cpd-openpages-operator
    app.kubernetes.io/managed-by: ibm-cpd-openpages-operator
    app.kubernetes.io/name: ibm-cpd-openpages-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: {{ .Values.global.operatorNS }}

