apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: {{ .Values.global.operatorNS }}
  labels:
    app.kubernetes.io/instance: ibm-cpd-openpages-operator
    app.kubernetes.io/managed-by: ibm-cpd-openpages-operator
    app.kubernetes.io/name: ibm-cpd-openpages-operator