apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-operator-controller-manager
  namespace: {{ .Values.global.operatorNS }}
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cert-manager-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: cert-manager-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cert-manager-operator
  strategy: {}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: cert-manager-operator
      creationTimestamp: null
      labels:
        name: cert-manager-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - resources:
            requests:
              cpu: 10m
              memory: 32Mi
          name: cert-manager-operator
          command:
            - /usr/bin/cert-manager-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: namespace-scope
                  key: namespaces
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: cert-manager-operator
            - name: RELATED_IMAGE_CERT_MANAGER_WEBHOOK
              value: 'registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:33308217d2226c2555eb18020710d16175295a8e349263a5435e4b158bbc735f'
            - name: RELATED_IMAGE_CERT_MANAGER_CA_INJECTOR
              value: 'registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:33308217d2226c2555eb18020710d16175295a8e349263a5435e4b158bbc735f'
            - name: RELATED_IMAGE_CERT_MANAGER_CONTROLLER
              value: 'registry.redhat.io/cert-manager/jetstack-cert-manager-rhel9@sha256:33308217d2226c2555eb18020710d16175295a8e349263a5435e4b158bbc735f'
            - name: RELATED_IMAGE_CERT_MANAGER_ACMESOLVER
              value: 'registry.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9@sha256:831e4b1e5aa6eed6fbb22f779ddbcb9c73e4bf6cc079d0c6652737a6a44e6320'
            - name: RELATED_IMAGE_CERT_MANAGER_ISTIOCSR
              value: 'registry.redhat.io/cert-manager/cert-manager-istio-csr-rhel9@sha256:9ea2c29a384b964cef14f853278821df3cd30320f25afab8823897192f67fc7e'
            - name: OPERAND_IMAGE_VERSION
              value: 1.16.5
            - name: ISTIOCSR_OPERAND_IMAGE_VERSION
              value: 0.14.0
            - name: OPERATOR_IMAGE_VERSION
              value: 1.16.1
            - name: OPERATOR_LOG_LEVEL
              value: '2'
            - name: TRUSTED_CA_CONFIGMAP_NAME
            - name: CLOUD_CREDENTIALS_SECRET_NAME
            - name: UNSUPPORTED_ADDON_FEATURES
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          imagePullPolicy: IfNotPresent
          image: 'registry.redhat.io/cert-manager/cert-manager-operator-rhel9@sha256:d30e755a266bb035d50e2b257e7a26c1fe6a5ccb66125576db99d537aa03ec27'
          args:
            - start
            - '--v=$(OPERATOR_LOG_LEVEL)'
            - '--trusted-ca-configmap=$(TRUSTED_CA_CONFIGMAP_NAME)'
            - '--cloud-credentials-secret=$(CLOUD_CREDENTIALS_SECRET_NAME)'
            - '--unsupported-addon-features=$(UNSUPPORTED_ADDON_FEATURES)'
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: cert-manager-operator-controller-manager
      terminationGracePeriodSeconds: 10
