apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-operator-controller-manager
  namespace: {{ .Values.global.instanceNS }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-operator-controller-manager
subjects:
- kind: ServiceAccount
  name: cert-manager-operator-controller-manager
  namespace: {{ .Values.global.operatorNS }}
