apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cognos-analytics-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: cognos-analytics
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/nickmerrett/cp4d-5.2-gitops.git
    targetRevision: main
    path: repos/cognos-analytics
    helm:
      valueFiles:
        - ../../values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
