apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: db2u-operator
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
    resources:
      - persistentvolumes
    verbs:
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - patch
      - update
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
      - podsecuritypolicies/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - use
      - watch
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
      - securitycontextconstraints/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
