apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: planning-analytics-instance-gitops
  namespace: openshift-gitops
  labels:
    scope: namespace
    product: planning-analytics
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://gitops-cp4d.github.io/non-olm-cp4d-gitops/repos
    targetRevision: 5.2.0+20250604.210250.1608
    chart: planning-analytics-instance
    helm:
      valuesObject:
        global:
          licenseAccept: true
          operatorNamespace: gitops-operator
          instanceNamespace: gitops-instance
          releaseVersion: 5.2.0
          tetheredNamespaces: []
          blockStorageClass: ocs-external-storagecluster-ceph-rbd
          fileStorageClass: ocs-external-storagecluster-cephfs
          imagePullPrefix: cp.icr.io
          imagePullSecret: ibm-entitlement-key
          installConfigImageDigest: sha256:f97f1b364a27acfe08b1c80d9ce91c25f07e6005a7ba821abf164c8e38925a04
          installConfigImageName: cpopen/cpd/olm-utils-v3
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
