apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-cpd-datarefinery-operator
  namespace: {{ .Values.global.operatorNS }}
  labels:
    null
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: ibm-cpd-datarefinery-operator
  strategy: {}
  template:
    metadata:
      annotations:
        cloudpakId: eb9998dcc5d24e3eb5b6fb488f750fe2
        cloudpakName: IBM Cloud Pak for Data
        productID: eb9998dcc5d24e3eb5b6fb488f750fe2
        productMetric: FREE
        productName: IBM Data Refinery
        productVersion: 11.0.0
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ibm-cpd-datarefinery-operator
        app.kubernetes.io/managed-by: ibm-cpd-datarefinery-operator
        app.kubernetes.io/name: ibm-cpd-datarefinery-operator
        control-plane: ibm-cpd-datarefinery-operator
        icpdsupport/addOnId: rshaper
        icpdsupport/app: operator
        icpdsupport/module: operator
        intent: projected
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - args:
            - --zap-log-level
            - error
            - --max-concurrent-reconciles
            - "1"
            - --reconcile-period
            - 0s
          env:
            - name: ANSIBLE_CALLBACK_WHITELIST
              value: profile_roles, profile_tasks
            - name: ANSIBLE_STDOUT_CALLBACK
              value: yaml
            - name: WATCH_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: namespaces
                  name: namespace-scope
                  optional: true
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: icr.io/cpopen/ibm-cpd-datarefinery-operator@sha256:bf59211212d5685c573ceefae985281b0f7bfa2e004b8dd04c1635623014f86a
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 15
            periodSeconds: 20
          name: ibm-cpd-datarefinery-operator-container
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 250Mi
              memory: 1Gi
            requests:
              cpu: 100m
              ephemeral-storage: 250Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
      serviceAccount: ibm-cpd-datarefinery-operator-serviceaccount
      serviceAccountName: ibm-cpd-datarefinery-operator-serviceaccount
      terminationGracePeriodSeconds: 10
