apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: ibm-wml
    app.kubernetes.io/managed-by: ibm-cpd-wml-operator
    app.kubernetes.io/name: ibm-wml
    olm.managed: "true"
    operators.coreos.com/ibm-cpd-wml-operator.cpd-watsonx-ai: ""
  name: wmlbases.wml.cpd.ibm.com
spec:
  conversion:
    strategy: None
  group: wml.cpd.ibm.com
  names:
    kind: WmlBase
    listKind: WmlBaseList
    plural: wmlbases
    singular: wmlbase
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The desired version of Watson Machine Learning
          jsonPath: .spec.version
          name: Version
          type: string
        - description: The desired build of Watson Machine Learning
          jsonPath: .status.buildNumber
          name: Build
          type: string
        - description: The status of Watson Machine Learning
          jsonPath: .status.wmlStatus
          name: Status
          type: string
        - description: Progress percentage
          jsonPath: .status.progress
          name: Percent
          type: string
        - description: The actual version of Watson Machine Learning
          jsonPath: .status.versions.reconciled
          name: Reconciled
          type: string
        - description: The age of Watson Machine Learning
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1beta1
      schema:
        openAPIV3Schema:
          description: WmlBase is the Schema for the wmlbases API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of WmlBase
              properties:
                blockStorageClass:
                  type: string
                docker_registry_prefix:
                  type: string
                fileStorageClass:
                  type: string
                ignoreForMaintenance:
                  default: false
                  type: boolean
                license:
                  properties:
                    accept:
                      default: false
                      type: boolean
                    license:
                      pattern: ^(Enterprise|Standard)$
                      type: string
                  required:
                    - accept
                    - license
                  type: object
                scaleConfig:
                  pattern: ^(small_mincpureq|small|medium)$
                  type: string
                shutdown:
                  pattern: ^(false|true|force)$
                  type: string
                storageClass:
                  type: string
                storageVendor:
                  pattern: ^(ocs||portworx)$
                  type: string
                version:
                  default: 5.2.0
                  type: string
              required:
                - license
              x-kubernetes-preserve-unknown-fields: true
            status:
              description: Status defines the observed state of WmlBase
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
