apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-cluster-${appSuffix}
  namespace: ${argocdNS}
  labels:
    scope: cluster
    product: software-hub
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: ${helmRepoURL}
    targetRevision: ${postgresql-cluster-version}
    chart: ${postgresql-cluster-chart}
    helm:
      valuesObject:
        global:
          operatorNamespace: ${operatorNS}
        ## patching when ccs is enabled
        # webhook:
        #   mutating:
        #     create: false
        #   validating:
        #     create: false
  project: default
