apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-cpd-watsonx-ai-ifm-operator
  namespace: {{ .Values.global.operatorNS }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: ibm-cpd-watsonx-ai-ifm-operator
  strategy: {}
  template:
    metadata:
      annotations:
        cloudpakId: 5e4c7dd451f14946bc298e18851f3746
        cloudpakName: IBM watsonx.ai
        productID: 3a6d4448ec8342279494bc22e36bc318
        productMetric: FREE
        productName: IBM Watsonx.ai
        productVersion: 11.0.0
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ibm-cpd-watsonx-ai-ifm-operator
        app.kubernetes.io/managed-by: ibm-cpd-watsonx-ai-ifm-operator
        app.kubernetes.io/name: ibm-cpd-watsonx-ai-ifm-operator
        control-plane: ibm-cpd-watsonx-ai-ifm-operator
        icpdsupport/addOnId: watsonx_ai_ifm
        icpdsupport/app: operator
        icpdsupport/module: ibm-cpd-watsonx-ai-ifm-operator
        intent: projected
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - args:
            - --zap-log-level
            - error
            - --max-concurrent-reconciles
            - "1"
            - --reconcile-period
            - 0s
          env:
            - name: ANSIBLE_CALLBACK_WHITELIST
              value: profile_roles, profile_tasks
            - name: ANSIBLE_STDOUT_CALLBACK
              value: yaml
            - name: WATCH_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: namespaces
                  name: namespace-scope
                  optional: true
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: icr.io/cpopen/ibm-cpd-watsonx-ai-ifm-operator@sha256:dc7a39552f7a2ce3263170f3f683cc88ee66c1648386f094a752cf5b37f2aac6
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: 100m
              ephemeral-storage: 1Gi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
      serviceAccount: ibm-cpd-watsonx-ai-ifm-operator-serviceaccount
      serviceAccountName: ibm-cpd-watsonx-ai-ifm-operator-serviceaccount
      terminationGracePeriodSeconds: 10
